server:
  port: 9191

spring:
  application:
    name: gateway-service
    
  cloud:
      gateway:
         discovery:
            locator:
               enabled: true
               
         globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "http://localhost:4200"
                allowedHeaders:
                  - content-type
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE

         routes:
         
            - id: master-service
              uri: lb://master-service
              predicates:
              - Path=/masters/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: master
                    fallbackUri: forward:/fallbacks/master
              
            - id: customer-service
              uri: lb://customer-service
              predicates:
              - Path=/customers/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: customer
                    fallbackUri: forward:/fallbacks/customer
              
            - id: product-service
              uri: lb://product-service
              predicates:
              - Path=/products/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: product
                    fallbackUri: forward:/fallbacks/product
            
            - id: invoice-service
              uri: lb://invoice-service
              predicates:
              - Path=/invoices/**

            
  profiles:
    active:
      - path # path | header | query are the other spring profiles for other strategies

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka # value will get overriden if passed from external config

  
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      customer:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowSize: 5
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

      product:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowSize: 5
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

      master:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowSize: 5
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      product:
        registerHealthIndicator: true
        maxRetryAttempts: 3
        waitDuration: 5s      

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG
