server:
  port: 9003
  servlet:
    context-path: /products
spring:
  application:
    name: product-service
    
  zipkin:
      base-url: http://localhost:9411/

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost