server:
  port: 9001
  servlet:
    context-path: /masters
spring:
  application:
    name: master-service
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/